# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splyttr', '0004_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bg_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
