# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('splyttr', '0005_auto_20160729_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tab',
            name='created',
        ),
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'%m/%d/%Y %H:%M'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 1, 18, 47, 28, 174787, tzinfo=utc), verbose_name=b'%m/%d/%Y %H:%M'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'%m/%d/%Y %H:%M'),
            preserve_default=False,
        ),
    ]
