# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splyttr', '0006_auto_20160901_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%m/%d/%Y %H:%M'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%m/%d/%Y %H:%M'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%m/%d/%Y %H:%M'),
        ),
    ]
