# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splyttr', '0008_auto_20160920_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='a_debtor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
