version: '2'

services:

  api:
    restart: always
    build: ./splyttr-api
    environment:
      - DEBUG=False
    env_file:
      - ./splyttr-api/ENV
    links:
      - db
    volumes:
      - staticfiles:/static

  db:
    restart: always
    image: postgres:9.6
    env_file:
      - ./splyttr-api/ENV
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:

  postgres:
    driver: local

  staticfiles:
    driver: local
