version: '2'

services:

  api:
    env_file:
      - ./ENV
    restart: always
    build: .
    links:
      - postgres

  postgres:
    env_file:
      - ./ENV
    restart: always
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
