# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splttr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='a_debtor',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='debtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
